language: generic 
sudo: required
services:
    - docker

before_install:
    - docker build -t alexandreferrari/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true alexandreferrari/docker-react npm run test